site_name: Soopace - Tutorials
site_url: https://simonjisu.github.io/Tutorials
repo_url: https://github.com/simonjisu/Tutorials

theme:
  name: "material"
  logo: img/logo/logo.png
  custom_dir: overrides
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.tracking
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags:
     tags_file: index.md
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/simonjisu
  analytics:
    provider: google
    property: G-3PRN7HGSG5